blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('popular/', views.popular, name="popular"),
    path('news/', views.news, name="news"),
    path('search/', views.search_results, name='search_result'),
    path('post/<str:slug>/', views.post_detail, name="post_detail_url"),
    path('post/<str:slug>/leave-comment', views.leave_comment, name='leave_comment'),
    path('category/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('register/', views.register, name="register"),
    path('contact/', views.contact, name="contact"),
]

kkkdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone 
from django.shortcuts import reverse

class Category(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('Ссылка', max_length=255, unique=True)
    image = models.ImageField('Картинка', blank=True)

    def get_absolute_url(self):
       return reverse('category_detail_url', kwargs={'slug':self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):  
        return self.title

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    slug = models.SlugField('Ссылка', max_length=255, unique=True)
    summary = models.TextField('Краткое описание')
    content = models.TextField('Описание')
    date = models.DateTimeField('Дата', default=timezone.now)
    image = models.ImageField('Картинка', blank=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    views = models.IntegerField('Просмотры', default=0)

    def get_absolute_url(self):
       return reverse('post_detail_url', kwargs={'slug':self.slug})

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):  
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField('ИМя автора', max_length=255)
    text = models.TextField('Текст комментария')
    date = models.DateTimeField('Дата коментария', default=timezone.now)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.author_name

class Contact(models.Model):
    name = models.CharField("Имя", max_length=255)
    last_name = models.CharField("Фамилия", max_length=255)
    email = models.EmailField("Емаил")
    phone = models.CharField("Телефон", max_length=255)
    message = models.TextField('Текст сообщения')
    date = models.DateTimeField("Дата", default=timezone.now)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return self.name

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm (UserCreationForm):
    username = forms.CharField(label="Никнейм", required=True, widget=forms.TextInput(attrs={"class":'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Пароль", required=True, widget=forms.PasswordInput(attrs={"class":'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Повторите пароль", required=True, widget=forms.PasswordInput(attrs={"class" :'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label="Емаил", required=True, widget=forms.TextInput(attrs={"class" :'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label="Имя", required=True, widget=forms.TextInput(attrs={"class" :'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label="Фамилия", required=True, widget=forms.TextInput(attrs={"class" :'form-control footer-input margin-b-20'}))

    class Meta:
        model = User 
        fields = ("first_name", "last_name", "email", "password1", "password2", "username",)
        
    def save (self, commit=True): 
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]

        if commit:
            user.save()
            return user

blog/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import Post, Category, Comment, Contact
from .forms import RegisterForm
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse


def index(request):
    news = Post.objects.order_by('-date')[:3]
    popular = Post.objects.filter(views__gt = 10)[:3]
    return render(request, 'blog/index.html', {'news':news, 'popular': popular})


def popular(request):
    popular = Post.objects.filter(views__gt = 10)
    return render(request, 'blog/popular.html', {'popular':popular})

def news(request):
    news = Post.objects.order_by('-date')
    return render(request, 'blog/news.html', {'news':news})
    
def category(request):
    category = Post.objects.order_by('-date')
    return render(request, 'blog/category.html', {'category':category})

def search_results(request):
    query = request.GET.get('search')
    search_obj = Post.objects.filter(
        Q(title__icontains = query) | Q(summary__icontains = query)
    )
    return render(request, 'blog/search_result.html', {'query':query, 'search_obj':search_obj})

def post_detail(request, slug):
    post = Post.objects.get(slug__iexact = slug)
    post.views += 1
    post.save()
    return render(request, 'blog/post_detail.html', {'post':post})

def category_detail(request, slug):
    category = Category.objects.get(slug__iexact = slug)
    posts = Post.objects.order_by('-date')
    return render(request, 'blog/category_detail.html', {'category':category, 'posts':posts})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RegisterForm()
    return render(request, 'blog/register.html', {'form':form})

def logout_views(request):
    logout(request)
    return redirect('index')

def leave_comment(request, slug):
    post = Post.objects.get(slug__iexact=slug)
    if  request.user.is_authenticated:
        user = request.user.first_name
        post.comment_set.create(
            author_name = user,
            text = request.POST.get('text')
        )
    else:
        post.comment_set.create(
            author_name = request.POST.get('name'), 
            text = request.POST.get('text')
    )
    return redirect(reverse('post_detail_url', args = (slug,)))


def contact(request):
    if request.method == 'POST':
        Contact.objects.create(
            name = request.POST.get('name'),
            last_name = request.POST.get('last_name'),
            email = request.POST.get('email'),
            phone = request.POST.get('phone'),
            message = request.POST.get('text')
        )
    return render(request, 'blog/contact.html')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        Сайт
        {% endblock %}
    </title>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=IM+Fell+Great+Primer+SC|Indie+Flower&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="font-family: 'IM Fell Great Primer SC', serif; font-size: 16px;">
   
<header id="header">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news' %}">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Категории</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Контакты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'popular' %}">Популярные посты</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Вход</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Выход</a>
        </li>
        {% endif %}
      </ul>
      <form action="{% url 'search_result' %}" method="GET" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" name ="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/statue.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <p style="color: black; font-size: 30px; font-family: 'Indie Flower', cursive; color:#332a2c; ">History of art department</p>
        <h1 style="color: black; font-size: 80px;">Hortense fiquet</h1 style="color: black; font-size: 80px;">
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/modern.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <p style="color: black; font-size: 30px; font-family: 'Indie Flower', cursive; color: #332a2c;">History of art department</p>
        <h1 style="color: black; font-size: 80px;">Modern classic</h1>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/beauty.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <p style="color: black; font-size: 30px; font-family: 'Indie Flower', cursive; color: #332a2c;">History of art department</p>
        <h1 style="color: black; font-size: 80px;">Discover beauty</h1 style="color: black; font-size: 80px;">
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/new.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <p style="color: black; font-size: 30px; font-family: 'Indie Flower', cursive; color: #332a2c;">History of art department</p>
        <h1 style="color: black; font-size: 80px;">New exhibition</h1 style="color: black; font-size: 80px;">
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% block content %}
    <p style="text-align: center; margin-top: 80px; font-family: 'Indie Flower', cursive; font-size: 20px; color: #A23A31">History of art department</p>
    <h1 style="text-align: center; font-size: 50px;">NATIONAL MUSEUM</h1>
    <main id="museum" style="width: 95%; margin-top: 40px; margin-bottom: 50px; margin-left: auto; margin-right: auto; display: flex; flex-wrap: wrap; justify-content: center;">
      <div class="content" style="width: 30%; margin: 0; justify-content: center; align-content: center; padding-left: 50px; padding-right: 50px; padding-top: 50px;">
        <p>Lorem ipsum dolor sit amet, consectetur estor adipi isicing elit, sed do eiusmod tempor este uterre incididui unt ut labore et dolore magna aliquaas. Ut enim ad minim veniam, quis mot nostrud desto exercitation est ullamco laboris nisi ut se aliquip ex ea commodos consequat. Duis aute irure et dolor in reprehender itinse voluptate velit esse cillum dolore eu fugiat do nulla pariatur deus ex.</p>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisic eli sed do eiusmod tempor incididunt ut labore et dolore si magna aliqua.</p>
      </div>
      <div class="content" style="width: 30%; margin: 0;">
        <img src="{% static 'img/museum.jpg' %}" style="width: 100%;" alt="">
      </div>
      <div class="content" style="width: 30%; margin: 0; justify-content: center; align-content: center; padding-left: 50px; padding-right: 50px; padding-top: 50px;">
        <p>Lorem ipsum dolor sit amet, consectetur dolore adipisicing eli sed do eiusmod tempor incididunt ut labore et dolore si magna aliqua. Ut enim ad minim veniam, quis ester nostrud e exercitation ullamco laboris nisi ut aliquip ex ea commodo ut consequat in Duis aute irure dolor in ut mag.</p>
        <button type="button" class="btn btn-outline-dark" style="margin-left: 100px; margin-top: 50px; transition: 0.6s;">View more</button>
      </div>
    </main>
    <div class="conterner-fluit">
      <div class="row">
          {% for post in news %}
          <div class="col-md-3">
            <a href="{{post.categories.get_absolute_url}}">
              <p>{{post.categories.title}}</p>
            </a>
            <a href="{{post.get_absolute_url}}">
              <h3>{{post.title}}</h3>
            </a>
            {% if post.image.url != null %}
            <a href="{{post.get_absolute_url}}">
              <img src="{{post.image.url}}" alt="" style="width: 100%;">
            </a>
            {% endif %}
              <p>{{post.summary}}</p>
              <em>{{post.date|date:"D j M, Y"}}</em>
          </div>
          {% endfor %}
      </div>
    </div>
    <content id="art" style="width: 100%; background-color: #e0e0d08a; display: flex; flex-wrap: wrap; margin-top: 50px; margin-bottom: 80px;">
      <div class="cont" style="width: 50%; padding-left: 40px; padding-right: 40px; padding-top: 20px;">
        <p style="font-family: 'Indie Flower', cursive; font-size: 20px; color: #A23A31; font-size: 15px;">The Museum archive</p>
        <h1 style="font-size: 40px;">WORKS OF ART</h1>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei usmod tempor incididunt ut labore et dolore</p>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do se eiusmod temps incididunt ut labore et sa dolore si magna aliqua. Ut enim ad minim veniam, inant quis nostrud e exercitation ullamco laboris nisi ut sen aliquip ex ea commodo insa consequat duis aute</p>
        <button type="button" class="btn btn-outline-dark" style="margin-left: 100px; margin-top: 50px; transition: 0.6s;">View more</button>
      </div>
      <div class="cont" style="width: 50%;">
        <img src="{% static 'img/art.jpg' %}" style="width: 100%;" alt="">
      </div>

    </content>
    {% endblock %}
  <footer class="page-footer font-small indigo" style="background-color: #c7c196; padding-top: 20px;">
    <div class="container text-center text-md-left">
      <div class="row">
        <div class="col-md-3 mx-auto">
          <img src="{% static 'img/logo.png' %}" style="width: 90px; margin-bottom: 20px;" alt="">
          <ul class="list-unstyled">
            <li>
              4639 street
            </li>
            <li>
              0521 04 52 48
            </li>
          </ul>
        </div>
        <hr class="clearfix w-100 d-md-none">
        <div class="col-md-3 mx-auto">
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Museum info</h5>
          <ul class="list-unstyled">
            <li>
              <a href="#!" style="color: black;">Events & Shows</a>
            </li>
            <li>
              <a href="#!" style="color: black;">Exhibitions</a>
            </li>
            <li>
              <a href="#!" style="color: black;">News & Updates</a>
            </li>
            <li>
              <a href="#!" style="color: black;">Buy Tickets</a>
            </li>
          </ul>
        </div>
        <hr class="clearfix w-100 d-md-none">
        <div class="col-md-3 mx-auto">
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Opening hours</h5>
          <ul class="list-unstyled">
            <li>
              Tue ‒ Thu: 9am ‒ 7pm
            </li>
            <li>
              Fri ‒ Sat: 9am ‒ 5pm
            </li>
            <li>
              Sun: 8am ‒ 6pm
            </li>
            <li>
              Mon: closed
            </li>
          </ul>
        </div>
        <hr class="clearfix w-100 d-md-none">
        <div class="col-md-3 mx-auto">
          <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Follow us</h5>

          <ul class="list-unstyled">
            <li>
              <a href="#!" style="color: black;">Vkontacte</a>
            </li>
            <li>
              <a href="#!" style="color: black;">Facebook</a>
            </li>
            <li>
              <a href="#!" style="color: black;">Instagram</a>
            </li>
            <li>
              <a href="#!" style="color: black;">Twitter</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <hr style="margin: 0;">
    <div class="footer-copyright text-center py-3">© 2020 
      <a href="#" style="color: black;"> xxx.com</a>
    </div>
  </footer>
    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>    
</body>
</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}

{% block title %}
    новости
{% endblock %}
{% block content %}
<div class="conterner-fluit" style="margin-bottom: 100px; margin-left: 150px;">
    <div class="row">
        {% for post in category %}
        <div class="col-md-3">
          <a href="{{post.categories.get_absolute_url}}">
            <p>{{post.categories.title}}</p>
          </a>
          {% if post.categories.image.url != null %}
          <a href="{{post.categories.get_absolute_url}}">
            <img src="{{post.categories.image.url}}" alt="" style="width: 100%;">
          </a>
          {% endif %}
        </div>
        {% endfor %}
    </div>
  </div>
{% endblock %}

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block title %}
    категории
{% endblock %}
{% block content %}
<div class="conterner-fluit">
    <div class="row">
        {% for post in category.post_set.all %}
        <div class="col-md-3">
          <a href="{{post.categories.get_absolute_url}}">
            <p>{{post.categories.title}}</p>
          </a>
          <a href="{{post.get_absolute_url}}">
            <h3>{{post.title}}</h3>
          </a>
          {% if post.image.url != null %}
          <a href="{{post.get_absolute_url}}">
            <img src="{{post.image.url}}" alt="" style="width: 100%;">
          </a>
          {% endif %}
            <p>{{post.summary}}</p>
            <em>{{post.date|date:"D j M, Y"}}</em>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block title %}
    контакт
{% endblock %}
{% block content %}
    <h1>Обратная связь</h1>
    <form action="{% url 'contact' %}" class="" method="POST">
        {% csrf_token %}
        <p>
            <label>Имя</label>
            <input type="text" name="name">
            <label>Фамилия</label>
            <input type="text" name="last_name">
        </p>
        <p>
            <label for="">Email</label>
            <input type="email" name="email">
        </p>
        <p>
            <label for="">Телефон</label>
            <input type="text" name="phone">
        <p>
            <label for="">Текст</label>
            <textarea name="text" id="" cols="30" rows="10"></textarea>
        </p>
        <button class="btn btn-success">
            Отправить
        </button>
    </form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}
    home
{% endblock %}
{% load static %}
{% block content %}

<p style="text-align: center; margin-top: 80px; font-family: 'Indie Flower', cursive; font-size: 20px; color: #A23A31">History of art department</p>
<h1 style="text-align: center; font-size: 50px;">NATIONAL MUSEUM</h1>
<main id="museum" style="width: 95%; margin-top: 40px; margin-bottom: 50px; margin-left: auto; margin-right: auto; display: flex; flex-wrap: wrap; justify-content: center;">
  <div class="content" style="width: 30%; margin: 0; justify-content: center; align-content: center; padding-left: 50px; padding-right: 50px; padding-top: 50px;">
    <p>Lorem ipsum dolor sit amet, consectetur estor adipi isicing elit, sed do eiusmod tempor este uterre incididui unt ut labore et dolore magna aliquaas. Ut enim ad minim veniam, quis mot nostrud desto exercitation est ullamco laboris nisi ut se aliquip ex ea commodos consequat. Duis aute irure et dolor in reprehender itinse voluptate velit esse cillum dolore eu fugiat do nulla pariatur deus ex.</p>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisic eli sed do eiusmod tempor incididunt ut labore et dolore si magna aliqua.</p>
  </div>
  <div class="content" style="width: 30%; margin: 0;">
    <img src="{% static 'img/museum.jpg' %}" style="width: 100%;" alt="">
  </div>
  <div class="content" style="width: 30%; margin: 0; justify-content: center; align-content: center; padding-left: 50px; padding-right: 50px; padding-top: 50px;">
    <p>Lorem ipsum dolor sit amet, consectetur dolore adipisicing eli sed do eiusmod tempor incididunt ut labore et dolore si magna aliqua. Ut enim ad minim veniam, quis ester nostrud e exercitation ullamco laboris nisi ut aliquip ex ea commodo ut consequat in Duis aute irure dolor in ut mag.</p>
    <button type="button" class="btn btn-outline-dark" style="margin-left: 100px; margin-top: 50px; transition: 0.6s;">View more</button>
  </div>
</main>
<content id="art" style="width: 100%; background-color: #e0e0d08a; display: flex; flex-wrap: wrap; margin-top: 50px; margin-bottom: 80px;">
  <div class="cont" style="width: 50%; padding-left: 40px; padding-right: 40px; padding-top: 20px;">
    <p style="font-family: 'Indie Flower', cursive; font-size: 20px; color: #A23A31; font-size: 15px;">The Museum archive</p>
    <h1 style="font-size: 40px;">WORKS OF ART</h1>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do ei usmod tempor incididunt ut labore et dolore</p>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do se eiusmod temps incididunt ut labore et sa dolore si magna aliqua. Ut enim ad minim veniam, inant quis nostrud e exercitation ullamco laboris nisi ut sen aliquip ex ea commodo insa consequat duis aute</p>
    <button type="button" class="btn btn-outline-dark" style="margin-left: 100px; margin-top: 50px; transition: 0.6s;">View more</button>
  </div>
  <div class="cont" style="width: 50%;">
    <img src="{% static 'img/art.jpg' %}" style="width: 100%;" alt="">
  </div>
</content>

<div class="conterner-fluit" style="margin-bottom: 100px; margin-left: 150px;">
  <div class="row">
      {% for post in category %}
      <div class="col-md-3">
        <a href="{{post.categories.get_absolute_url}}">
          <p>{{post.categories.title}}</p>
        </a>
        {% if post.categories.image.url != null %}
        <a href="{{post.categories.get_absolute_url}}">
          <img src="{{post.categories.image.url}}" alt="" style="width: 100%;">
        </a>
        {% endif %}
      </div>
      {% endfor %}
  </div>
  <h1>Популярные посты</h1>
  <div class="row">
      {% for post in popular %}
      <div class="col-md-3">
        {% if post.image.url != null %}
        <a href="{{post.get_absolute_url}}">
          <img src="{{post.image.url}}" alt="" style="width: 100%;">
        </a>
        {% endif %}
          <p>{{post.summary}}</p>
          <em>{{post.date|date:"D j M, Y"}}</em>
      </div>
      {% endfor %}
  </div>
</div>
  {% endblock %}

blog/templates/blog/news.html
{% extends 'blog/base.html' %}

{% block title %}
    новости
{% endblock %}
{% block content %}
<div class="conterner-fluit">
  <div class="row">
      {% for post in news %}
      <div class="col-md-3">
        <a href="{{post.categories.get_absolute_url}}">
          <p>{{post.categories.title}}</p>
        </a>
        <a href="{{post.get_absolute_url}}">
          <h3>{{post.title}}</h3>
        </a>
        {% if post.image.url != null %}
        <a href="{{post.get_absolute_url}}">
          <img src="{{post.image.url}}" alt="" style="width: 100%;">
        </a>
        {% endif %}
          <p>{{post.summary}}</p>
          <em>{{post.date|date:"D j M, Y"}}</em>
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

blog/templates/blog/popular.html
{% extends 'blog/base.html' %}

{% block title %}
    популярные посты
{% endblock %}
{% block content %}
<h1>Популярные посты</h1>
<div class="row">
    {% for post in popular %}
    <div class="col-md-3">
      {% if post.image.url != null %}
      <a href="{{post.get_absolute_url}}">
        <img src="{{post.image.url}}" alt="" style="width: 100%;">
      </a>
      {% endif %}
        <p>{{post.summary}}</p>
        <em>{{post.date|date:"D j M, Y"}}</em>
        <em>{{post.views}}</em>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block title %}
    форма регистрации
{% endblock %}
{% block content %}
<section class="container">
    <h3>Форма регистрации</h3>
    {% if user.is_authenticated %}
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-success">Зарегистрироваться</button>
    </form>
    {% endif %}
</section>
{% endblock %}